data:
 test: fdddsdfsdfsdfsdf1111
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
hostip: localhost
server:
  port: 9903
spring:
  rabbitmq:
    host: 47.101.11.64
    port: 5672
    username: admin
    password: admin
  kafka:
    bootstrap-servers: 47.101.11.64:9093
    producer:
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      #      auto-offset-reset: earliest
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://localhost:3306/db_insurance?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  redis:
    password: passwd123
    cluster:
      nodes:
        - 192.168.10.31:7901
        - 192.168.10.31:7902
        - 192.168.10.41:7901
        - 192.168.10.41:7902
        - 192.168.10.51:7901
        - 192.168.10.51:7902

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${hostip}
    instance-id: ${hostip}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/


#开启feign支持hystrix  (注意，一定要开启，旧版本默认支持，新版本默认关闭)
# #修改调用超时时间（默认是1秒就算超时）
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000


#公共模块的配置，可以不配
# 异常邮件发送
exception:
  send:
    enable: true
    emil: licc@rayeye.cn

# 打印日志
logging:
  #控制台日志输出级别,这里设置的级别，控制xml文件中console控制台的输出，不设置默认info
  level:
    com.rayeye.insurance.order: trace
  #配置日志输出
  config: classpath:log4j2-dev.xml


